---
apiVersion: v1
kind: Secret
metadata:
  name: pavithrabada-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rhdh-deploy/pavithrabada-gateway-gitops
